# Details
title:       Future Imperfect
description: Jekyll port of Future Imperfect template by HTML5 UP
url:         http://seshaljain.github.io/future-imperfect-jekyll/
baseurl:     /future-imperfect-jekyll

#Author
author:
  name:      'Seshal Jain'
  url:       http://seshal.me

paginate:    3
paginate_path: "/:num/"

# Permalinks
permalink:   /:categories/:title/

# Build settings
# destination: dest 
# source:      src # Commented out because Github Pages does not allow different source directory
markdown:    kramdown
highlighter: pygments

# Gems
gems:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - github-pages
