# Details
title:       Future Imperfect
description: Jekyll port of Future Imperfect template by HTML5 UP
url:         http://gertclaus.github.io
baseurl:     

#Author
author:
  name:      'John Doe'

paginate:    3
paginate_path: "/:num/"

# Permalinks
permalink:   /:categories/:title/

# Build settings
# destination: dest
# source:      src # Removed because Github Pages does not allow different source directory
markdown:    kramdown
highlighter: rouge

# Gems
gems: [jekyll-paginate]
